spring:
  application:
    name: game-service
  datasource:
    hikari:
      one:
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://127.0.0.1:3306/game?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&rewriteBatchedStatements=true&allowMultiQueries=true
         username: root
         password: root
         maximum-pool-size: 30
      two:
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://127.0.0.1:3306/cif?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&rewriteBatchedStatements=true&allowMultiQueries=true
         username: root
         password: root
         maximum-pool-size: 30




server:
  port: 9000